import Address from './faker/address';
import Ancient from './faker/ancient';
import App from './faker/app';
import Avatar from './faker/avatar';
import * as Bank from './faker/bank';
import * as Beer from './faker/beer';
import * as Bitcoin from './faker/bitcoin';
import * as Book from './faker/book';
import * as Boolean from './faker/boolean';
import * as Business from './faker/business';
import * as Cat from './faker/cat';
import * as ChuckNorris from './faker/chuck-norris';
import * as Coffee from './faker/coffee';
import * as Color from './faker/color';
import * as Commerce from './faker/commerce';
import * as Company from './faker/company';
import * as Compass from './faker/compass';
import * as Crypto from './faker/crypto';
import * as Date from './faker/date';
import * as Demographic from './faker/demographic';
import * as DragonBall from './faker/dragon-ball';
import * as Educator from './faker/educator';
import Fake from './faker/fake';
import * as File from './faker/file';
import * as Fillmurray from './faker/fillmurray';
import * as Food from './faker/food';
import * as Friends from './faker/friends';
import * as GameOfThrones from './faker/game-of-thrones';
import * as Hacker from './faker/hacker';
import * as HarryPotter from './faker/harry-potter';
import * as Hipster from './faker/hipster';
import * as Internet from './faker/internet';
import * as LordOfTheRings from './faker/lord-of-the-rings';
import * as LoremFlickr from './faker/lorem-flickr';
import * as LoremPixel from './faker/lorem-pixel';
import * as Lorem from './faker/lorem';
import * as Matz from './faker/matz';
import * as Music from './faker/music';
import * as Name from './faker/name';
import * as Number from './faker/number';
import * as PhoneNumber from './faker/phone-number';
import * as Placeholdit from './faker/placeholdit';
import * as Pokemon from './faker/pokemon';
import * as Random from './faker/random';
import * as RickAndMorty from './faker/rick-and-morty';
import * as RockBand from './faker/rock-band';
import * as RuPaul from './faker/ru-paul';
import * as SlackEmoji from './faker/slack-emoji';
import * as Space from './faker/space';
import * as StarWars from './faker/star-wars';
import * as Superhero from './faker/superhero';
import * as Team from './faker/team';
import * as Time from './faker/time';
import * as TwinPeaks from './faker/twin-peaks';
import Twitter from './faker/twitter';
import * as University from './faker/university';
import * as Vehicle from './faker/vehicle';
import * as Zelda from './faker/zelda';

class Faker {
  constructor() {
    this.Address = new Address(this);
    this.Ancient = new Ancient(this);
    this.App = new App(this);
    this.Avatar = new Avatar(this);
    this.Bank = Bank;
    this.Beer = Beer;
    this.Bitcoin = Bitcoin;
    this.Book = Book;
    this.Boolean = Boolean;
    this.Business = Business;
    this.Cat = Cat;
    this.ChuckNorris = ChuckNorris;
    this.Coffee = Coffee;
    this.Color = Color;
    this.Commerce = Commerce;
    this.Company = Company;
    this.Compass = Compass;
    this.Crypto = Crypto;
    this.Date = Date;
    this.Demographic = Demographic;
    this.DragonBall = DragonBall;
    this.Educator = Educator;
    this.Fake = new Fake(this);
    this.File = File;
    this.Fillmurray = Fillmurray;
    this.Food = Food;
    this.Friends = Friends;
    this.GameOfThrones = GameOfThrones;
    this.Hacker = Hacker;
    this.HarryPotter = HarryPotter;
    this.Hipster = Hipster;
    this.Internet = Internet;
    this.LordOfTheRings = LordOfTheRings;
    this.LoremFlickr = LoremFlickr;
    this.LoremPixel = LoremPixel;
    this.Lorem = Lorem;
    this.Matz = Matz;
    this.Music = Music;
    this.Name = Name;
    this.Number = Number;
    this.PhoneNumber = PhoneNumber;
    this.Placeholdit = Placeholdit;
    this.Pokemon = Pokemon;
    this.Random = Random;
    this.RickAndMorty = RickAndMorty;
    this.RockBand = RockBand;
    this.RuPaul = RuPaul;
    this.SlackEmoji = SlackEmoji;
    this.Space = Space;
    this.StarWars = StarWars;
    this.Superhero = Superhero;
    this.Team = Team;
    this.Time = Time;
    this.TwinPeaks = TwinPeaks;
    this.Twitter = new Twitter(this);
    this.University = University;
    this.Vehicle = Vehicle;
    this.Zelda = Zelda;
  }
}

module.exports = new Faker();
